### ISSUE TITLE
Parse placeholder for other players & Javascript placeholders

### ISSUE THREAD

**Issue by BiGUNMAN** [extendedclip/PlaceholderAPI#6]
A command like /papi parse (player) or /papi parsep - (for distinction) to parse placeholders for other online players, not just you, would be extremely useful.

In addition, I noticed that large javascript placeholders such as:
http://pastebin.com/fd4neanx
Randomly do and do not work. Sometimes doing the following to the javascripts works: http://pastebin.com/2de6ZSXC --- (The placeholder is used as a click requirement in DeluxeMenus).

**Comment by extendedclip** [comment]
I like the idea of the command and will add it soon. 

With your javascript issue, you should compare strings like this:
``` Javascript
"%player_name%".equals("extended_clip")
```
rather than using the == operator. 

When comparing numbers you should first convert the string to int
``` Javascript
parseInt("%vault_eco_balance%") >= 100;
```

you can read more about it here
http://stackoverflow.com/questions/5630123/javascript-string-integer-comparisons

**Comment by BiGUNMAN** [comment]
@extendedclip 
If you could clarify a bit, that would be amazing. I currently wrote this up: https://pastebin.com/2NG6jw4M but am getting this issue: http://i.imgur.com/rKxX7Zt.png. I'd refer to that stackoverflow post but I barely get it : \
